[package]
edition = "2024"
license = "Apache-2.0"
name = "pegainfer-engine"
version = "0.1.0"

[dependencies]
fastrace = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
