"""AOT-export the GLM5.2 CuTe DSL fp8 blockwise GEMMs for the decode wide route.

For each production projection shape x wide-route decode bucket this compiles
the kernel-lab tcgen05 GEMM (`Fp8BlockwiseGemmTcgen05`, tuned TILE_CFG) via
`cute.compile` and calls `export_to_c`, yielding a PIC object with the cubin
embedded plus a header exposing a host launch entry — no Python and no
tensormap code needed at runtime. A generated `glm52_fp8_dsl_gen.h` wraps the
per-prefix entries into one uniform dispatch table consumed by
`csrc/glm52/glm52_fp8_dsl_gemm.c`.

Shapes are compile-time constants in the artifact (the header's tensor structs
carry only a data pointer), so one entry per (rows, n, k). The kernel tiles
rows in 64-row M tiles (grid.x), so every wide-route decode bucket through 96
exports; per-rows tile configs come from `tile_cfg` (multi-M-tile shapes drop
the CTA-starvation compensation the single-tile table carries).

Needs torch + CUDA + nvidia-cutlass-dsl (JIT compiles on the build box) and
the kernel-lab sources; skips itself via a content hash when nothing changed.
"""

import argparse
import hashlib
import json
import os
import sys

WIDE_ROUTE_ROWS = [16, 32, 48, 64, 96]
# (tag, n, k) — the four wide-route projections (docs/models/glm52/
# fp8-blockwise-gemm-lab.md); tags feed generated symbol names.
SHAPES = [
    ("qb", 16384, 2048),
    ("oproj", 6144, 16384),
    ("gateup", 4096, 6144),
    ("down", 6144, 2048),
]

GEMM_PARAMS = ["mA", "mB", "mSFA", "mSFB", "mD"]
RED_PARAMS = ["mP", "mOut"]


def content_hash(benches_dir: str) -> str:
    h = hashlib.sha256()
    for path in (
        __file__,
        os.path.join(benches_dir, "kernel_lab/units/fp8_gemm_dsl_tc_kernel.py"),
        os.path.join(benches_dir, "kernel_lab/units/fp8_gemm_dsl_tc.py"),
    ):
        with open(path, "rb") as f:
            h.update(f.read())
    h.update(repr((WIDE_ROUTE_ROWS, SHAPES)).encode())
    return h.hexdigest()


def adapter_block(name: str, params: list) -> str:
    decls = "\n".join(
        f"    {name}_Tensor_{p}_t {p} = {{p{i}}};" for i, p in enumerate(params)
    )
    args = ", ".join(f"&{p}" for p in params)
    ptr_params = ", ".join(f"void *p{i}" for i in range(len(params)))
    return f"""
static {name}_Kernel_Module_t {name}_mod;
static void {name}_load(void) {{ {name}_Kernel_Module_Load(&{name}_mod); }}
static int32_t {name}_run({ptr_params}, cudaStream_t stream) {{
{decls}
    return cute_dsl_{name}_wrapper(&{name}_mod, {args}, stream);
}}
"""


def emit_gen_header(out_dir: str, entries: list) -> None:
    parts = ["// Generated by export_glm52_fp8_dsl.py — do not edit.", "#pragma once"]
    for e in entries:
        parts.append(f'#include "{e["name"]}.h"')
        if e["split_k"] > 1:
            parts.append(f'#include "{e["name"]}_red.h"')
    for e in entries:
        parts.append(adapter_block(e["name"], GEMM_PARAMS))
        if e["split_k"] > 1:
            parts.append(adapter_block(e["name"] + "_red", RED_PARAMS))
    parts.append("""
typedef int32_t (*g52dsl_gemm_fn)(void *, void *, void *, void *, void *, cudaStream_t);
typedef int32_t (*g52dsl_red_fn)(void *, void *, cudaStream_t);
typedef void (*g52dsl_load_fn)(void);

typedef struct {
    int32_t m, n, k, split_k;
    g52dsl_load_fn load;
    g52dsl_gemm_fn run;
    g52dsl_load_fn red_load;
    g52dsl_red_fn red_run;
} g52dsl_entry_t;

static const g52dsl_entry_t G52DSL_TABLE[] = {""")
    for e in entries:
        name, sk = e["name"], e["split_k"]
        red_load = f"{name}_red_load" if sk > 1 else "0"
        red_run = f"{name}_red_run" if sk > 1 else "0"
        parts.append(
            f'    {{{e["rows"]}, {e["n"]}, {e["k"]}, {sk}, '
            f"{name}_load, {name}_run, {red_load}, {red_run}}},"
        )
    parts.append("""};

enum { G52DSL_TABLE_LEN = sizeof(G52DSL_TABLE) / sizeof(G52DSL_TABLE[0]) };
""")
    with open(os.path.join(out_dir, "glm52_fp8_dsl_gen.h"), "w") as f:
        f.write("\n".join(parts))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--benches-dir", required=True)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    digest = content_hash(args.benches_dir)
    manifest_path = os.path.join(args.out_dir, "manifest.json")
    if os.path.exists(manifest_path):
        with open(manifest_path) as f:
            old = json.load(f)
        if old.get("hash") == digest and all(
            os.path.exists(os.path.join(args.out_dir, o))
            for o in old.get("objects", [])
        ):
            print("cutedsl export up to date")
            return

    sys.path.insert(0, args.benches_dir)
    import torch
    import cuda.bindings.driver as cuda_drv
    import cutlass.cute as cute
    from cutlass.cute.runtime import from_dlpack
    from kernel_lab.units.fp8_gemm_dsl_tc import tile_cfg
    from kernel_lab.units.fp8_gemm_dsl_tc_kernel import (
        Fp8BlockwiseGemmTcgen05,
        _SplitKReduce,
    )

    def wrap(t, dtype):
        return from_dlpack(t.view(dtype).unsqueeze(-1), assumed_align=16)

    entries = []
    objects = []
    stream = cuda_drv.CUstream(0)
    for tag, n, k in SHAPES:
        for rows in WIDE_ROUTE_ROWS:
            block_n, split_k = tile_cfg(rows, n, k)
            name = f"g52dsl_{tag}_r{rows}"
            mA = wrap(
                torch.zeros(rows, k, dtype=torch.uint8, device="cuda"),
                torch.float8_e4m3fn,
            )
            mB = wrap(
                torch.zeros(n, k, dtype=torch.uint8, device="cuda"),
                torch.float8_e4m3fn,
            )
            mSFA = wrap(
                torch.zeros(rows, k // 128, dtype=torch.float32, device="cuda"),
                torch.float32,
            )
            mSFB = wrap(
                torch.zeros(n // 128, k // 128, dtype=torch.float32, device="cuda"),
                torch.float32,
            )
            out = torch.zeros(rows, n, dtype=torch.bfloat16, device="cuda")
            if split_k > 1:
                partials = torch.zeros(
                    split_k, rows, n, dtype=torch.float32, device="cuda"
                )
                mD = from_dlpack(partials.permute(1, 2, 0), assumed_align=16)
                red = cute.compile(
                    _SplitKReduce(split_k), mD, wrap(out, torch.bfloat16), stream
                )
                red.export_to_c(args.out_dir, name + "_red")
                objects.append(name + "_red.o")
            else:
                mD = wrap(out, torch.bfloat16)
            gemm = Fp8BlockwiseGemmTcgen05(block_n=block_n, split_k=split_k)
            compiled = cute.compile(gemm, mA, mB, mSFA, mSFB, mD, stream)
            compiled.export_to_c(args.out_dir, name)
            objects.append(name + ".o")
            entries.append(
                {"name": name, "rows": rows, "n": n, "k": k, "split_k": split_k}
            )
            print(f"exported {name} (block_n={block_n} split_k={split_k})")

    emit_gen_header(args.out_dir, entries)
    with open(manifest_path, "w") as f:
        json.dump({"hash": digest, "entries": entries, "objects": objects}, f, indent=1)
    print(f"cutedsl export: {len(entries)} entries, {len(objects)} objects")


if __name__ == "__main__":
    main()
