//! HF-oracle accuracy gates for the GLM5.2 bricks.
//!
//! Each gate replays a seeded input (generated by `tools/accuracy/glm52_oracle.py`
//! against the pinned transformers `glm_moe_dsa` modeling code) through the
//! engine and asserts the outputs land on hardcoded probe constants within an
//! RMS-scaled tolerance. All gates are `#[ignore]` — they require GPU +
//! checkpoint (and EP8 needs 8×H200 + NCCL).
//!
//! Run any gate:
//! ```text
//! OPENINFER_TEST_MODEL_PATH=/data/models/GLM-5.2-FP8 \
//!   cargo test --release -p openinfer-glm52 --features glm52 --lib mla_oracle -- --ignored --nocapture
//! ```

mod bookend;
mod indexer;
mod layer;
mod layer_ep8;
mod mla;
